services:
  # Nginx
  nginx:
    image: nginx:1.19.7-alpine
    container_name: editor-nginx
    environment:
      - VIRTUAL_HOST=e.editorium.net
      - LETSENCRYPT_HOST=e.editorium.net
    depends_on:
      - editor
      - nest
      - postgres
    volumes:
      - ./nginx/nginx.conf.server:/etc/nginx/nginx.conf

  # Клиентская часть редактора
  editor:
    build:
      context: ./editor
      dockerfile: Dockerfile.prod
    container_name: editor-editor
    command: serve /app/dist -l 3000
    restart: unless-stopped

  # API редактора (Nest)
  nest:
    build:
      context: ./nestApi
      dockerfile: Dockerfile.prod
    container_name: editor-nest
    command: npm run start:prod
    restart: unless-stopped
    environment:
      - MODE=production
      - PORT=3002
    depends_on:
      - postgres

  # Postgres
  # BD: editor
  # User: editor
  # Password: dt52posQP00P
  postgres:
    image: postgres:16.2
    container_name: editor-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: dt52posQP00P
      POSTGRES_USER: editor
      POSTGRES_DB: editor
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dbdata6: {}
  postgres:

networks:
  default:
    external:
      name: nginx-proxy