version: "3.3"

services:

  # Nginx
  nginx:
    build: ./nginx
    container_name: editor-nginx
    depends_on:
      - editor
      - nest_api
      - postgres_db
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf
    networks:
      - editorium-network

  # Клиентская часть редактора
  editor:
    build:
      context: ./editor
      dockerfile: Dockerfile.dev
    container_name: editor-editor
    command: npm run dev
    environment:
      - SITE_URL=editorium.local
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./editor/src:/app/src
    networks:
      - editorium-network

  # API редактора (Nest)
  nest_api:
    build:
      context: ./nestApi
      dockerfile: Dockerfile.dev
    container_name: nest_api
    command: npm run start:dev
    restart: unless-stopped
    environment:
      - MODE=development
      - PORT=3002
    depends_on:
      - postgres_db
    networks:
      - editorium-network
    volumes:
      - ./nestApi/src:/app/src

  # Postgres
  # BD: editor
  # User: editor
  # Password: dt52posQP00P
  postgres_db:
    image: postgres:13-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: sguen35GPA
      POSTGRES_USER: postgres
      POSTGRES_DB: editor
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - editorium-network


volumes:
  postgres_db:

networks:
  editorium-network:
    driver: bridge