version: "3.9"

services:

  # API редактора
  editor_api:
    command: npm run dev
    environment:
      - MODE=development
    volumes:
      - ./editorApi/src:/usr/src/app/src

  # БД редактора
  editor_db:
    ports:
      - 27017:27017

  # Клиентская часть редактора
  editor:
    build:
      context: ./editor
      dockerfile: Dockerfile.dev
    command: npm run start
    stdin_open: true
    tty: true
    volumes:
      - ./editor/src:/usr/src/app/src

  # Nginx
  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/default.conf