version: "3.3"

services:
  # Nginx
  nginx:
    image: nginx:1.19.7-alpine
    container_name: editor-nginx
    environment:
      - VIRTUAL_HOST=editorium.net
      - LETSENCRYPT_HOST=editorium.net
    depends_on:
      - editor
      - nest_api
#      - postgres_db
    volumes:
      - ./nginx/nginx.conf.server:/etc/nginx/nginx.conf

  # Клиентская часть редактора
  editor:
    build:
      context: ./editor
      dockerfile: Dockerfile.prod
    container_name: editor-editor
    command: serve /app/dist -l 3000
    restart: unless-stopped

  # API редактора (Nest)
  nest_api:
    build:
      context: ./nestApi
      dockerfile: Dockerfile.prod
    container_name: nest_api
    command: npm run start:prod
    restart: unless-stopped
    environment:
      - MODE=production
      - PORT=3002
#    depends_on:
#      - postgres_db

  # Postgres
  # BD: editor
  # User: editor
  # Password: dt52posQP00P
#  postgres_db:
#    image: postgres:13-alpine
#    container_name: postgres_db
#    restart: unless-stopped
#    environment:
#      POSTGRES_PASSWORD: sguen35GPA
#      POSTGRES_USER: postgres
#      POSTGRES_DB: editor
#    volumes:
#      - postgres_db:/var/lib/postgresql/data


#volumes:
#  postgres_db:

networks:
  default:
    external:
      name: nginx-proxy
