FROM node:14.15.3-alpine3.12
WORKDIR /app

COPY package.json ./

RUN npm install
RUN npm install -D @swc/cli @swc/core

COPY . .

RUN npm run build
RUN npm prune --production

CMD ["npm", "start"]
EXPOSE 3003
