FROM node:16.13.1-alpine3.14
WORKDIR /app
COPY package*.json ./

# Поставить все пакеты из package.json
# Поставить сервер
RUN npm install && npm install -g serve

COPY . .

# Создать папку если не существует
RUN mkdir -p dist

# Скопировать файл serve.json
COPY ./serve.json /app/dist

# Собрать пакет
RUN npm run build