FROM node:16.13.1-alpine3.14
WORKDIR /app
COPY package*.json ./

# Поставить все пакеты из package.json
# Поставить сервер
RUN npm install && npm install -g serve

COPY . .

# Скопировать файл serve.json
RUN mkdir dist
COPY ./serve.json /app/dist

# Собрать пакет
RUN npm run build