
events {}

http {
    include mime.types;

    server {
        listen 80;
        server_name localhost;
        root /sites;

        location /api {
            proxy_pass http://editor_api:3001;
            rewrite ^\/api\/(.*) /$1 break;
        }

        location /editor/ {
            proxy_pass http://editor:3000/;
        }

        location /kia {
            return 200 'Hello from Kia site';
        }
    }
}