// import { MiscTypes } from 'types/miscTypes'
// import {useEffect, useState} from 'react'
// import {MainTabDataType} from 'editor/special/MainTab/MainTab'
// import {useDispatch, useSelector} from 'react-redux'
// import {AppState} from 'store/rootReducer'
// import StoreSettingsTypes from 'store/settings/settingsTypes'